services:

  uftrace-recv:
    container_name: uftrace-recv
    image: uftrace-recv:latest
    environment:
      UFTRACE_DATA: "uftrace-data"
    ports:
      - "8090"
    command: /usr/src/uftrace/uftrace recv -d /home/app/uftrace-data --libmcount-path=/usr/src/uftrace --port 8888
    healthcheck:
      test: "exit 0"
      interval: 30s
      timeout: 10s
      retries: 5

  uftrace-rest-api-server:
    container_name: uftrace-rest-api-server
    image: uftrace-rest-api-server:latest
    depends_on:
      uftrace-recv:
        condition: service_healthy
    environment:
      UFTRACE_DATA: "uftrace-data"
      UFTRACE_RECV: "uftrace-recv"
    ports:
      - "8090"
      - "9090"
    # command: /usr/src/uftrace/uftrace record -d /home/app/uftrace-data --libmcount-path=/usr/src/uftrace --host uftrace-recv ./twitter-clone-rust
    # command: /usr/src/uftrace/uftrace record -d /home/app/uftrace-data --libmcount-path=/usr/src/uftrace ./twitter-clone-rust
    command: tail -f /dev/null